# Generated by Django 6.0.1 on 2026-02-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailings",
            old_name="repicients",
            new_name="recipients",
        ),
    ]
